language: ruby
install: script/bootstrap
rvm:
  - 2.2
env:
  - SUITE=ruby
  - SUITE=cucumber1-3
  - SUITE=cucumber2-4
  - SUITE=minitest4
  - SUITE=minitest5
  - SUITE=rspec2-1
  - SUITE=rspec3-0
  - SUITE=rspec3-1
  - SUITE=rspec3-2
  - SUITE=testunit
script: script/cibuild
notifications:
  email: false
